/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafe_app;

 import java.util.Calendar;
 import java.util.GregorianCalendar;
 import java.awt.Color;
 import java.text.SimpleDateFormat;
 import java.util.Random;
/**
 *
 * @author brian
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
 double[] drink = new double[5];
 double[] cake = new double[8];
 double[] cost = new double[3]; 
 double[]   i  = new double[10];
 double[]   p   = new double[20];
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jchkLattle = new javax.swing.JCheckBox();
        jchkIced = new javax.swing.JCheckBox();
        jchkExpresso = new javax.swing.JCheckBox();
        jchkCapuccino = new javax.swing.JCheckBox();
        jchkIce = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtxtCapuccino = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtxtExpresso = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtxtIced = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtxtLattle = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jtxtIce = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlblDrinkscost = new javax.swing.JLabel();
        jlblServicecharge = new javax.swing.JLabel();
        jlblCakescost = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlblTax = new javax.swing.JLabel();
        jlblSubtotal = new javax.swing.JLabel();
        jlblTotal = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jchkCoffee = new javax.swing.JCheckBox();
        jchkRed = new javax.swing.JCheckBox();
        jchkForest = new javax.swing.JCheckBox();
        jchkQueens = new javax.swing.JCheckBox();
        jchkBreezy = new javax.swing.JCheckBox();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtxtQueens = new javax.swing.JTextPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtxtForest = new javax.swing.JTextPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        jtxtCoffee = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        jtxtRed = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jtxtBreezy = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jchkLattle.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jchkLattle.setText("LATTLE");
        jchkLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchkLattleMouseClicked(evt);
            }
        });
        jchkLattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkLattleActionPerformed(evt);
            }
        });

        jchkIced.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jchkIced.setText("ICED LATTLE");
        jchkIced.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchkIcedMouseClicked(evt);
            }
        });
        jchkIced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkIcedActionPerformed(evt);
            }
        });

        jchkExpresso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jchkExpresso.setText("EXPRESSO");
        jchkExpresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchkExpressoMouseClicked(evt);
            }
        });
        jchkExpresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkExpressoActionPerformed(evt);
            }
        });

        jchkCapuccino.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jchkCapuccino.setText("CAPUCCINO");
        jchkCapuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchkCapuccinoMouseClicked(evt);
            }
        });
        jchkCapuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkCapuccinoActionPerformed(evt);
            }
        });

        jchkIce.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jchkIce.setText("ICE TEA");
        jchkIce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchkIceMouseClicked(evt);
            }
        });
        jchkIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkIceActionPerformed(evt);
            }
        });

        jtxtCapuccino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtCapuccino.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jtxtCapuccino.setText("0");
        jtxtCapuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCapuccinoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtxtCapuccino);

        jtxtExpresso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtExpresso.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jtxtExpresso.setText("0");
        jtxtExpresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtExpressoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtxtExpresso);

        jtxtIced.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtIced.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jtxtIced.setText("0");
        jtxtIced.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtIcedMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtxtIced);

        jScrollPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jtxtLattle.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jtxtLattle.setText("0");
        jtxtLattle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtLattleMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jtxtLattle);

        jtxtIce.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtIce.setFont(new java.awt.Font("Trajan Pro", 1, 14)); // NOI18N
        jtxtIce.setText("0");
        jtxtIce.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtIceMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(jtxtIce);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkLattle)
                    .addComponent(jchkIced)
                    .addComponent(jchkExpresso)
                    .addComponent(jchkCapuccino)
                    .addComponent(jchkIce))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane12))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkLattle)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jchkIced, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jchkExpresso)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jchkCapuccino)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jchkIce)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("DRINKS COST");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("CAKES COST");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("SERVICE CHARGE");

        jlblDrinkscost.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblDrinkscost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblDrinkscost.setText("0");
        jlblDrinkscost.setToolTipText("");
        jlblDrinkscost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblServicecharge.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblServicecharge.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblServicecharge.setText("5");
        jlblServicecharge.setToolTipText("");
        jlblServicecharge.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblCakescost.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblCakescost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCakescost.setText("0");
        jlblCakescost.setToolTipText("");
        jlblCakescost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlblServicecharge, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblDrinkscost, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblCakescost, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblDrinkscost, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCakescost, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblServicecharge, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("TAX");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("TOTAL");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("SUB-TOTAL");

        jlblTax.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblTax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTax.setText("0");
        jlblTax.setToolTipText("");
        jlblTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblSubtotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblSubtotal.setText("0");
        jlblSubtotal.setToolTipText("");
        jlblSubtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlblTotal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTotal.setText("0");
        jlblTotal.setToolTipText("");
        jlblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblSubtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jlblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jchkCoffee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jchkCoffee.setText("Coffee cake");
        jchkCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchkCoffeeMouseClicked(evt);
            }
        });

        jchkRed.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jchkRed.setText("Red Velvet Cake");
        jchkRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchkRedMouseClicked(evt);
            }
        });

        jchkForest.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jchkForest.setText("Black Forest Cake");
        jchkForest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchkForestMouseClicked(evt);
            }
        });

        jchkQueens.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jchkQueens.setText("Queens  Cake");
        jchkQueens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchkQueensMouseClicked(evt);
            }
        });

        jchkBreezy.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jchkBreezy.setText("Breezy Cake");
        jchkBreezy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchkBreezyMouseClicked(evt);
            }
        });

        jtxtQueens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtQueens.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jtxtQueens.setText("0");
        jtxtQueens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtQueensMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(jtxtQueens);

        jtxtForest.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtForest.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jtxtForest.setText("0");
        jtxtForest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtForestMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(jtxtForest);

        jtxtCoffee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtCoffee.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jtxtCoffee.setText("0");
        jtxtCoffee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCoffeeMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jtxtCoffee);

        jtxtRed.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtRed.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jtxtRed.setText("0");
        jtxtRed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtRedMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(jtxtRed);

        jtxtBreezy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jtxtBreezy.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jtxtBreezy.setText("0");
        jtxtBreezy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtBreezyMouseClicked(evt);
            }
        });
        jScrollPane11.setViewportView(jtxtBreezy);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchkQueens)
                            .addComponent(jchkBreezy))
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jScrollPane7))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchkRed)
                            .addComponent(jchkForest)
                            .addComponent(jchkCoffee))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane9)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jchkCoffee))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jchkRed)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jchkForest)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jchkQueens)
                        .addGap(18, 18, 18)
                        .addComponent(jchkBreezy)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jtxtReceipt.setColumns(20);
        jtxtReceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Castellar", 2, 48)); // NOI18N
        jLabel1.setText("Cafe Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jButton1.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jButton1.setText("TOTAL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jbtnReset.setText("RECEIPT");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Lucida Fax", 1, 10)); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbtnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jbtnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jchkLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchkLattleMouseClicked
        double cLattle =Double.parseDouble(jlblDrinkscost.getText());
        double Lattle =Double.parseDouble(jtxtLattle.getText());
        double iLattle =300;

        if(jchkLattle.isSelected()){
            i[0] = (Lattle*iLattle)+cLattle;
            String pDrink =String.format("%.2f", i[0]);
            p[0] = Lattle*iLattle;
            String iDrink = String.format("%.2f", p[0]);
            jlblDrinkscost.setText(pDrink);
            jtxtLattle.setText(iDrink);
        }
    }//GEN-LAST:event_jchkLattleMouseClicked

    private void jchkLattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkLattleActionPerformed

    }//GEN-LAST:event_jchkLattleActionPerformed

    private void jchkIcedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchkIcedMouseClicked
        double cIced =Double.parseDouble(jlblDrinkscost.getText());
        double Iced =Double.parseDouble(jtxtIced.getText());
        double iIced =200;

        if(jchkIced.isSelected()){
            i[1] = (Iced*iIced)+cIced;
            String pDrink =String.format("%.2f", i[1]);
            p[1] = Iced*iIced;
            String iDrink = String.format("%.2f", p[1]);
            jtxtIced.setText(iDrink);
            jlblDrinkscost.setText(pDrink);

        }
    }//GEN-LAST:event_jchkIcedMouseClicked

    private void jchkIcedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkIcedActionPerformed

    }//GEN-LAST:event_jchkIcedActionPerformed

    private void jchkExpressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchkExpressoMouseClicked
        double cExpresso =Double.parseDouble(jlblDrinkscost.getText());
        double Expresso =Double.parseDouble(jtxtExpresso.getText());
        double iExpresso =100;

        if(jchkExpresso.isSelected()){
            i[2] = (Expresso*iExpresso)+cExpresso;
            String pDrink =String.format("%.2f", i[2]);
            p[2] = Expresso*iExpresso;
            String iDrink = String.format("%.2f", p[2]);
            jlblDrinkscost.setText(pDrink);
            jtxtExpresso.setText(iDrink);
        }
    }//GEN-LAST:event_jchkExpressoMouseClicked

    private void jchkExpressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkExpressoActionPerformed

    }//GEN-LAST:event_jchkExpressoActionPerformed

    private void jchkCapuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchkCapuccinoMouseClicked
        double cCapuccino =Double.parseDouble(jlblDrinkscost.getText());
        double Capuccino =Double.parseDouble(jtxtCapuccino.getText());
        double iCapuccino =50;

        if(jchkCapuccino.isSelected()){
            i[3] = (Capuccino*iCapuccino)+cCapuccino;
            String pDrink =String.format("%.2f", i[3]);
            p[3] = Capuccino*iCapuccino;
            String iDrink = String.format("%.2f", p[3]);
            jlblDrinkscost.setText(pDrink);
            jtxtCapuccino.setText(iDrink);
        }
    }//GEN-LAST:event_jchkCapuccinoMouseClicked

    private void jchkCapuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkCapuccinoActionPerformed

    }//GEN-LAST:event_jchkCapuccinoActionPerformed

    private void jchkIceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchkIceMouseClicked
        double cIce =Double.parseDouble(jlblDrinkscost.getText());
        double Ice =Double.parseDouble(jtxtIce.getText());
        double iIce =150;

        if(jchkIce.isSelected()){
            i[4] = (Ice*iIce)+cIce;
            String pDrink =String.format("%.2f", i[3]);
            p[4] = Ice*iIce;
            String iDrink = String.format("%.2f", p[4]);
            jlblDrinkscost.setText(pDrink);
            jtxtIce.setText(iDrink);
        }
    }//GEN-LAST:event_jchkIceMouseClicked

    private void jchkIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkIceActionPerformed

    }//GEN-LAST:event_jchkIceActionPerformed

    private void jtxtCapuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCapuccinoMouseClicked
        jtxtCapuccino.setText(null);
    }//GEN-LAST:event_jtxtCapuccinoMouseClicked

    private void jtxtExpressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtExpressoMouseClicked
        jtxtExpresso.setText(null);
    }//GEN-LAST:event_jtxtExpressoMouseClicked

    private void jtxtIcedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIcedMouseClicked
        jtxtIced.setText(null);
    }//GEN-LAST:event_jtxtIcedMouseClicked

    private void jtxtLattleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtLattleMouseClicked
        jtxtLattle.setText(null);
    }//GEN-LAST:event_jtxtLattleMouseClicked

    private void jtxtIceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIceMouseClicked
        jtxtIce.setText(null);
    }//GEN-LAST:event_jtxtIceMouseClicked

    private void jchkCoffeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchkCoffeeMouseClicked
        double cCoffee =Double.parseDouble(jlblCakescost.getText());
        double Coffee =Double.parseDouble(jtxtCoffee.getText());
        double iCoffee =200;

        if(jchkCoffee.isSelected()){
            i[5] = (Coffee*iCoffee)+cCoffee;
            String pCake =String.format("%.2f", i[5]);
            p[5] = Coffee*iCoffee;
            String iCake = String.format("%.2f", p[5]);
            jlblCakescost.setText(pCake);
            jtxtCoffee.setText(iCake);
        }
    }//GEN-LAST:event_jchkCoffeeMouseClicked

    private void jchkRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchkRedMouseClicked
        double cRed =Double.parseDouble(jlblCakescost.getText());
        double Red =Double.parseDouble(jtxtRed.getText());
        double iRed =150;

        if(jchkRed.isSelected()){
            i[6] = (Red*iRed)+cRed;
            String pCake =String.format("%.2f", i[6]);
            p[6] = Red*iRed;
            String iCake = String.format("%.2f", p[6]);
            jlblCakescost.setText(pCake);
            jtxtRed.setText(iCake);
        }
    }//GEN-LAST:event_jchkRedMouseClicked

    private void jchkForestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchkForestMouseClicked
        double cForest =Double.parseDouble(jlblCakescost.getText());
        double Forest =Double.parseDouble(jtxtForest.getText());
        double iForest =200;

        if(jchkForest.isSelected()){
            i[7] = (Forest*iForest)+cForest;
            String pCake =String.format("%.2f", i[7]);
            p[7] = Forest*iForest;
            String iCake = String.format("%.2f", p[7]);
            jlblCakescost.setText(pCake);
            jtxtForest.setText(iCake);
        }
    }//GEN-LAST:event_jchkForestMouseClicked

    private void jchkQueensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchkQueensMouseClicked
        double cQueens =Double.parseDouble(jlblCakescost.getText());
        double Queens =Double.parseDouble(jtxtQueens.getText());
        double iQueens =150;

        if(jchkQueens.isSelected()){
            i[8] = (Queens*iQueens)+cQueens;
            String pCake =String.format("%.2f", i[8]);
            p[8] = Queens*iQueens;
            String iCake = String.format("%.2f", p[8]);
            jlblCakescost.setText(pCake);
            jtxtQueens.setText(iCake);
        }
    }//GEN-LAST:event_jchkQueensMouseClicked

    private void jchkBreezyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchkBreezyMouseClicked
        double cBreezy =Double.parseDouble(jlblCakescost.getText());
        double Breezy =Double.parseDouble(jtxtBreezy.getText());
        double iBreezy =500;

        if(jchkBreezy.isSelected()){
            i[8] = (Breezy*iBreezy)+cBreezy;
            String pCake =String.format("%.2f", i[8]);
            p[8] = Breezy*iBreezy;
            String iCake = String.format("%.2f", p[8]);
            jlblCakescost.setText(pCake);
            jtxtBreezy.setText(iCake);
        }
    }//GEN-LAST:event_jchkBreezyMouseClicked

    private void jtxtQueensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtQueensMouseClicked
        jtxtQueens.setText(null);
    }//GEN-LAST:event_jtxtQueensMouseClicked

    private void jtxtForestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtForestMouseClicked
        jtxtForest.setText(null);
    }//GEN-LAST:event_jtxtForestMouseClicked

    private void jtxtCoffeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCoffeeMouseClicked
        jtxtCoffee.setText(null);
    }//GEN-LAST:event_jtxtCoffeeMouseClicked

    private void jtxtRedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtRedMouseClicked
        jtxtRed.setText(null);
    }//GEN-LAST:event_jtxtRedMouseClicked

    private void jtxtBreezyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtBreezyMouseClicked
        jtxtBreezy.setText(null);
    }//GEN-LAST:event_jtxtBreezyMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        drink[0] = Double.parseDouble(jlblDrinkscost.getText());
        drink[1] = Double.parseDouble(jlblCakescost.getText());
        drink[2] = Double.parseDouble(jlblServicecharge.getText());

        double cTotal1 = (drink[0]+drink[1]+drink[2]);

        String iTaxTotal = String.format("%.2f", cTotal1/100);
        jlblTax.setText(iTaxTotal);

        double subTotal = (cTotal1);
        String iSubtotal =String.format("%.2f", subTotal);
        jlblSubtotal.setText(iSubtotal);

        double allTotal = (cTotal1);
        double fTotal = allTotal+ cTotal1/100;
        String iTotal =String.format("%.2f", fTotal);
        jlblTotal.setText(iTotal);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        drink[0] = Double.parseDouble(jtxtLattle.getText());
        drink[1] = Double.parseDouble(jtxtIced.getText());
        drink[2] = Double.parseDouble(jtxtExpresso.getText());
        drink[3] = Double.parseDouble(jtxtCapuccino.getText());
        drink[4] = Double.parseDouble(jtxtIce.getText());

        cake[0] = Double.parseDouble(jtxtCoffee.getText());
        cake[1] = Double.parseDouble(jtxtRed.getText());
        cake[2] = Double.parseDouble(jtxtForest.getText());
        cake[3] = Double.parseDouble(jtxtQueens.getText());
        cake[4] = Double.parseDouble(jtxtBreezy.getText());

        cost[0]= Double.parseDouble(jlblSubtotal.getText());
        cost[1]= Double.parseDouble(jlblTax.getText());
        cost[2]= Double.parseDouble(jlblTotal.getText());
        //========================================================
        int refs;
        refs= 1325+ (int) (Math.random()*4238);
        //int ref =(refs);
        //========================================================
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime=new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate=new SimpleDateFormat("dd-MM-YY");
        Tdate.format(timer.getTime());
        //=========================================================
        jtxtReceipt.append(" \t\n Cafe management System: \n\n"+
            "Refference:\t\t"+ refs +
            "\n=========================\t\t"+
            "\nLattle:\t\t"+ drink[0] +
            "\nIced Lattle:\t\t"+drink[1]+
            "\nExpresso:\t\t"+drink[2]+
            "\nCapuccinno:\t\t"+drink[3]+
            "\nIce Tea:\t\t"+drink[4]+

            "\n=========================\t\t"+
            "\nCoffee cake(s):\t\t\t"+cake[0]+
            "\nRed Velvet Cake(s):\t\t"+cake[1]+
            "\nBlack Cake(s):\t\t\t"+cake[2]+
            "\nQueens Cake(s):\t\t"+cake[3]+
            "\nBreezy Cake(s):\t\t\t"+cake[4]+
            "\n\nDate: "+Tdate.format(timer.getTime())+
            "\t\tTime: "+tTime.format(timer.getTime())+

            "\n=========================\t\t"+
            "\nSubtotal: \t"+cost[0]+
            "\nTax: \t"+cost[1]+
            "\nTotal: \t"+cost[2]+
            "\n=========================\t\t"+
            "\n\n\t\tThank you \n");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jlblDrinkscost.setText("0");
        jlblCakescost.setText("0");
        jlblServicecharge.setText("0");
        jlblTax.setText("0");
        jlblTotal.setText("0");
        jlblSubtotal.setText("0");
        jtxtLattle.setText("0");
        jtxtIced.setText("0");
        jtxtCapuccino.setText("0");
        jtxtIce.setText("0");
        jtxtCoffee.setText("0");
        jtxtRed.setText("0");
        jtxtForest.setText("0");
        jtxtQueens.setText("0");
        jtxtBreezy.setText("0");
        jtxtExpresso.setText("0");
        jtxtReceipt.setText(null);
        jchkLattle.setSelected(false);
        jchkIced.setSelected(false);
        jchkExpresso.setSelected(false);
        jchkCapuccino.setSelected(false);
        jchkIce.setSelected(false);
        jchkCoffee.setSelected(false);
        jchkRed.setSelected(false);
        jchkForest.setSelected(false);
        jchkQueens.setSelected(false);
        jchkBreezy.setSelected(false);
        cost[0]= Double.parseDouble(jlblSubtotal.getText());
        cost[1]= Double.parseDouble(jlblTax.getText());
        cost[2]= Double.parseDouble(jlblTotal.getText());

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JCheckBox jchkBreezy;
    private javax.swing.JCheckBox jchkCapuccino;
    private javax.swing.JCheckBox jchkCoffee;
    private javax.swing.JCheckBox jchkExpresso;
    private javax.swing.JCheckBox jchkForest;
    private javax.swing.JCheckBox jchkIce;
    private javax.swing.JCheckBox jchkIced;
    private javax.swing.JCheckBox jchkLattle;
    private javax.swing.JCheckBox jchkQueens;
    private javax.swing.JCheckBox jchkRed;
    private javax.swing.JLabel jlblCakescost;
    private javax.swing.JLabel jlblDrinkscost;
    private javax.swing.JLabel jlblServicecharge;
    private javax.swing.JLabel jlblSubtotal;
    private javax.swing.JLabel jlblTax;
    private javax.swing.JLabel jlblTotal;
    private javax.swing.JTextPane jtxtBreezy;
    private javax.swing.JTextPane jtxtCapuccino;
    private javax.swing.JTextPane jtxtCoffee;
    private javax.swing.JTextPane jtxtExpresso;
    private javax.swing.JTextPane jtxtForest;
    private javax.swing.JTextPane jtxtIce;
    private javax.swing.JTextPane jtxtIced;
    private javax.swing.JTextPane jtxtLattle;
    private javax.swing.JTextPane jtxtQueens;
    private javax.swing.JTextArea jtxtReceipt;
    private javax.swing.JTextPane jtxtRed;
    // End of variables declaration//GEN-END:variables
}
